export const types: any[] = [
        {name: 'Normal', value: 'Normal'},
        {name: 'Fire', value: 'Fire'},
        {name: 'Water', value: 'Water'},
        {name: 'Grass', value: 'Grass'},
        {name: 'Flying', value: 'Flying'},
        {name: 'Fighting', value: 'Fighting'},
        {name: 'Poison', value: 'Poison'},
        {name: 'Electric', value: 'Electric'},
        {name: 'Ground', value: 'Ground'},
        {name: 'Rock', value: 'Rock'},
        {name: 'Psychic', value: 'Psychic'},
        {name: 'Ice', value: 'Ice'},
        {name: 'Bug', value: 'Bug'},
        {name: 'Ghost', value: 'Ghost'},
        {name: 'Steel', value: 'Steel'},
        {name: 'Dragon', value: 'Dragon'},
        {name: 'Dark', value: 'Dark'},
        {name: 'Fairy', value: 'Fairy'},
]